# Generated by Django 4.1.3 on 2022-11-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/products/', verbose_name='Изображение'),
        ),
    ]
