# Generated by Django 4.1.3 on 2022-11-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images/products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('SALE', 'sale'), ('NEW', 'new'), ('HOT', 'hot'), ('NONE', 'none')], default='NEW', max_length=5, null=True, verbose_name='Метка'),
        ),
    ]
