# Generated by Django 4.1.3 on 2022-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=None, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
