# Generated by Django 4.1.3 on 2022-11-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
