# Generated by Django 4.1.3 on 2022-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_image_productsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
